const fs=require('fs'),assert=require('assert/strict'),path=require('path');
const root=__dirname;
const xml=fs.readFileSync(path.join(root,'AndroidManifest.xml'),'utf8');
const java=fs.readFileSync(path.join(root,'src/mx/usaer02e/portal/LauncherActivity.java'),'utf8');
assert(!xml.includes('<uses-permission'));
assert(xml.includes('android:allowBackup="false"'));
assert(xml.includes('android:usesCleartextTraffic="false"'));
assert(xml.includes('android:minSdkVersion="24"'));
assert(xml.includes('android:targetSdkVersion="35"'));
assert(java.includes('https://red-neuronal-usaer-2e.streamlit.app/'));
assert(!java.includes('getIntent()'));
assert(!/import\s+android\.webkit|new\s+WebView/.test(java));
assert(!java.includes('SharedPreferences'));
assert(java.includes('putBinder("android.support.customtabs.extra.SESSION", null)'));
assert(java.includes('if (state == null) openPortal()'));
const apk=fs.readFileSync(process.argv[2] || path.join(root,'../../output/mobile/USAER-02E-Android-1.0.0.apk'));
assert.equal(apk.subarray(0,2).toString(),'PK');
assert(apk.length>10000 && apk.length<1000000);
console.log('Artifact and launcher security smoke checks: OK');
